server:
  port: 8080


spring:
  application:
    name: LOAN-MANAGEMENT

  datasource:
    url: jdbc:mysql://localhost:3306/loan_management
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  redis:
    host: localhost
    port: 6379
    cache:
      redis:
        time-to-live: 120000